layout_spectrum: 0.9193549
typography_spectrum: 0.6756272
color:
  saturation: 0.7661826
  lightness: 0.8843321
  brandStrength: 0.06854586
  rhythmicContrast: 0.3136564
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Mariusz Busilo fotografia
